Traceback (most recent call last):
  File "/home/tobias/Documents/DRONE-F1/utils/CLI.py", line 103, in __call__
    self.__execute(str(*args))
  File "/home/tobias/Documents/DRONE-F1/utils/CLI.py", line 96, in __execute
    result: str = target(*[x for x in splitInput[:ind] + splitInput[ind + int(ind != 0):] if x not in self.P_ARGS.union(self.D_ARGS)])
  File "/home/tobias/Documents/DRONE-F1/utils/CLI.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "/home/tobias/Documents/DRONE-F1/main.py", line 109, in _start
    module.activate()
  File "/home/tobias/Documents/DRONE-F1/communication/CommunicationInterface.py", line 42, in activate
    self._connect()
  File "/home/tobias/Documents/DRONE-F1/communication/LocalUDP.py", line 72, in _connect
    self.__socket.bind((self.__bc, self.__port))
OSError: [Errno 98] Address already in use
